# it is intended that this be used exclusive of all other docker-compose.*yml files in CI
version: "2.3"
services:
  web:
    # use master if NAME is unavailable
    image: "${PATCHSET_TAG}"
    links:
      - postgres
      - redis
      - cassandra
    environment:
      ENCRYPTION_KEY: facdd3a131ddd8988b14f6e4e01039c93cfa0160
      RAILS_ENV: test
      RAILS_DB_NAME_TEST: 'canvas_test'
      RAILS_DB_HOST: postgres
      RAILS_DB_PASSWORD: ''
      DATABASE_URL: "postgres://postgres@postgres:5432/canvas_test"
      RANDOMIZE_SEQUENCES: 1
      RERUNS_RETRY: $RERUNS_RETRY
      MAX_FAIL: $MAX_FAIL

  redis:
    image: starlord.inscloudgate.net/jenkins/redis:alpine

  postgres:
    image: starlord.inscloudgate.net/jenkins/postgres:9.5

  cassandra:
    image: starlord.inscloudgate.net/jenkins/cassandra:2.2
    environment:
      CASSANDRA_START_RPC: 'true'
