development:
  bucket_name: development-bucket
  access_key_id: access_key
  secret_access_key: secret_key
  region: us-east-1

test:
  bucket_name: test-bucket
  access_key_id: access_key
  secret_access_key: secret_key
  region: us-east-1
  
production:
  bucket_name: "<%= ENV['S3_BUCKET_NAME'] %>"
  access_key_id: "<%= ENV['S3_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['S3_ACCESS_KEY'] %>"
  region: "<%= ENV['AWS_REGION'] %>"
